name: Cypress Tests

on: [push]

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.2

      - name: Install dependencies
        run: yarn install
             npm install cypress

      - name: Run E2E tests
        run: yarn cypress run
        
